<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.35" />
        <PackageReference Include="IBM.Data.DB2.iSeries" Version="7.1.0" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0-rc.2.25502.107" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.0-rc.2.25502.107" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.0" />
        <PackageReference Include="MySqlConnector" Version="2.3.7" />
        <PackageReference Include="NUnit" Version="3.14.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
        <PackageReference Include="System.Data.Odbc" Version="10.0.0-rc.2.25502.107" />
        <PackageReference Include="System.Text.Json" Version="10.0.0-rc.2.25502.107" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\PStructure\PStructure.csproj" />
    </ItemGroup>

</Project>
