version: '3.1'

services:
  db2:
    image: ibmcom/db2
    container_name: db2
    privileged: true
    ports:
      - "50000:50000"
    environment:
      - DB2INST1_PASSWORD=db2inst1-pwd
      - LICENSE=accept
      - DBNAME=testdb
    volumes:
      - db2data:/database

volumes:
  db2data:
