CREATE TABLE IF NOT EXISTS PdoExample (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IS_ACTIVE BOOLEAN NOT NULL,
    STATUS CHAR(1) NOT NULL,
    AGE TINYINT UNSIGNED NOT NULL,
    SMALL_NUMBER SMALLINT NOT NULL,
    LARGE_NUMBER INT NOT NULL,
    VERY_LARGE_NUMBER BIGINT NOT NULL,
    HEIGHT FLOAT NOT NULL,
    WEIGHT DOUBLE NOT NULL,
    PRICE DECIMAL(18,2) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DATE_COMPACT CHAR(8) NOT NULL,
    DATE_WITH_TIME CHAR(19) NOT NULL,
    DATE_EU CHAR(10) NOT NULL,
    DATE_US CHAR(10) NOT NULL,
    DATE_CENTURY CHAR(7) NOT NULL
    );
